### ISSUE TITLE
File replacement is not tracked in user access log

### ISSUE THREAD

**Issue by ryansanford** [flywheel-io/core#1129]
File replacement is logically equivalent to (modify) or (delete + create). Modify and delete are subject to the user access log, and thus file replace should also be.

**Comment by nagem** [comment]
We only track access, not modification in the access log. Is this a request to also track modification of all files and containers?

**Comment by nagem** [comment]
Sorry, we also track deletion.

**Comment by nagem** [comment]
I agree that this should be considered a delete in the current implementation. It would be a modification in the new implementation of versioned files.

**Comment by AshleyAncona** [comment]
Is this dependent on formalize file replace logic at all?
