### ISSUE TITLE
Enable docker image push on non-master branches, without code change.

### ISSUE THREAD

**Issue by ryansanford** [flywheel-io/core#1148]
Occasionally, we want automated push of docker images for non-master branches for lower friction deployment on integration test systems. It would be more appropriate to enabled this as-needed via a CI setting, rather than needing to add then remove that intent from the .travis.yml

Suggest standardizing on an environment variable (`$CD_BRANCH_NAMES`) that could contain a list (delimiter choice open to implementer) of branch names. That environment variable could be set in the travis-ci config, and .travis.yml would be changed to push up docker image `flywheel/core:$TRAVIS_BRANCH.latest` only if `TRAVIS_BRANCH` matched that list.

**Comment by kofalt** [comment]
Yes please! I want this badly.

I don't understand the "without code change" part of the issue title, or the branch whitelist paragraph.

I think you're suggesting that we whitelist when we want non-master branch images? I guess I would suggest just always having an image on every commit. But maybe that won't work or would be inconvenient for reasons I'm not aware of.

**Comment by ryansanford** [comment]
Here's an example of what we do now "with code change" that I want to get away from. https://github.com/flywheel-io/core/commit/6cdd51536841e8b7eb679e0b55700f5e8fac2f62

**Comment by kofalt** [comment]
Ah, so basically codifying that exception case into something dev-configurable. Sure.

**Comment by ryansanford** [comment]
This was resolved by #1156
