### ISSUE TITLE
Don't silently skip missing files on download

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#119]
<a href="https://github.com/gsfr"><img src="https://avatars3.githubusercontent.com/u/712594?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gsfr](https://github.com/gsfr)**
_Wednesday Jan 06, 2016 at 20:06 GMT_
_Originally opened as https://github.com/scitran/core/issues/119_

----

We are currently silently skipping missing or unreadable files on download. As @kofalt points out, this is fundamentally opposed to our data management mission and must be corrected asap.

However, considerable edge cases exist. For example, how do we handle files being legitimately deleted, in parallel to a long-running download operation?

Also, we don't want to inform the user of a (potentially irrelevant) problem 3 hours into a large download and proceed to abort and purge all downloaded data.

We used to check for files during the download preflight, but that was deemed to slow. Let's again explore our options here. This pattern would allow us to mark files as being part of a download and delay physical removal until the download completes.

@kofalt, @ryansanford: Happy to hear your thoughts.

@rentzso: Let's take this on together next week.

**Comment by ehlertjd** [comment]
Closed with #1245
