### ISSUE TITLE
Update "old" device origins to new format

### ISSUE THREAD

**Issue by nagem** [flywheel-io/core#1200]
In #1151 we updated items in the devices table to have object ids instead of strings, as well as a few other changes. In that process, the origin generated for each request was changed from:
 
`{"origin": {"id": "a somewhat human readable string", "type": "device"}}`

to

`{"origin": {"id": <object_id>, "type": "device"}}`

***

New files would have the new format for their origin, but existing files would still have the old format. This makes display hard in the flywheel UI. The "new" device origins show unhelpful information: 
<img width="338" alt="screen shot 2018-05-11 at 3 15 17 pm" src="https://user-images.githubusercontent.com/5702596/39944945-2a0de034-552e-11e8-88ac-387d3e09e997.png">
For the new format's UI issue, we are properly joining the device objects so that can be fixed in the frontend. 

***

The old style causes errors when attempting to join device information for the "old" origins:
`{"status_code": 500, "message": "'reaper_FolderReaper_var_scitran_data_testdata_download' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string", "request_id": "c986e97e-1526070893"}`

We should update all files in the system that have an `origin.type` of `device` and an `origin.id` that is not in the format of an ObjectId. I believe that is a better solution than patching `join_origin` so all file origins in the system will have the same format.

***

I did notice also that "null" origins: (`{"origin": { "type": "unknown", "id": null }`) caused a similar issue, so a change to the `join_origin` function should be made regardless:
`{"status_code": 500, "message": "'None' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string", "request_id": "505d57cb-1526069936"}`

**Comment by nagem** [comment]
I began work on the db upgrade, it can be found on this branch: `origin-device-fix`

https://github.com/flywheel-io/core/commit/bb9235587d5aae97e116d4800441513838f31e67

**Comment by ambrussimon** [comment]
Closing resolved issue.
