### ISSUE TITLE
Allow after_id=<_id> pagination in addition to skip+limit

### ISSUE THREAD

**Issue by nagem** [flywheel-io/core#1203]
Relates to #1191 

Using `?filter=_id>X` as a method to support `after_id` pagination behavior would only work if the primary (only) sort order is `_id`. There were some initial brainstorming ideas that I will document below:

---
Also, here's how to implement `after=id` even if mongo is being irritable:

Suppose after doc A, and first ordering is by X. Fetch doc A, get A.X, run your query with added filter `X >= A.X`. Pop results of the front until A is found & removed. Send.

----
_Would not work (Added for visibility)_

Alternatively, a utility function that uses aggregation pipeline: user filter (`$match`), `$sort`, after_id filter, `$limit`

NOTE: @nagem Had a good point that the aggregation pipeline wouldn't work because you're still not sorting by id, so NVM! 

---
Using the workaround for ES bucket pagination - using a pagination ticket to store "previously seen" _ids, when user requests next page (by referencing ticket), do find similar to below:
```
find({ 
    "_id": { "$nin": seenIds }
}).sort({ "normal_sort_key": 1 }).limit(20);
```
not sure how Mongo behaves when you start sending it `$nin`s with >1k keys

**Comment by ambrussimon** [comment]
Closed by #1262 - see current limitations there.
