### ISSUE TITLE
Ensure new Flywheel SDK checks downloaded files are not truncated.

### ISSUE THREAD

**Issue by cgc** [flywheel-io/core#1225]
I've started writing scripts that make use of the new Flywheel SDK and was wondering if the issue https://github.com/flywheel-io/sdk/issues/14 would be a concern with the new code. Happy to search through the code to figure this out if y'all are short on bandwidth. Thanks!

**Comment by ehlertjd** [comment]
Hi @cgc, I believe that this was resolved server-side in #1205. I'm inclined to wait to see if the problem arises again before attempting to address it in the new SDK.

**Comment by ehlertjd** [comment]
We will continue to try to address this server side if it comes up again.
