### ISSUE TITLE
Multi-file downloads hanging on object storage 

### ISSUE THREAD

**Issue by gsfr** [flywheel-io/core#1232]
Behavior at stanfordlabs instance, which has object storage enabled:
* Multi-file downloads, such as one entire acquisition or files from multiple acquisitions, hang for extended periods with no user-feedback before data starts coming in, as well as what appears to be before each large file.
* If one of the files is *too large*, the downloaded tar file is incomplete and cannot be opened with Mac Finder.
* If the first file is *too large*, the Flywheel UI disappears and a non-user-friendly error message is shown.
```
{"status_code": 504, "message": "Nginx: gateway timeout."}
```

This behavior represents a significant deterioration of the user experience and should be considered a bug as well as blocker to deploying object storage.

cc @AshleyAncona @ryansanford @lmperry

**Comment by ambrussimon** [comment]
Prematurely closed by storage-plugins merge.
