### ISSUE TITLE
No way to add negative match to gear rules for classification

### ISSUE THREAD

**Issue by ehlertjd** [flywheel-io/core#1236]
The old way of doing this was setting something like: `File Classification: ^((?!non-image).)+$`. This still works if the *only* classification is `Non-Image`, but as soon as there's a second classification this rule no longer matches correctly.

**Comment by ehlertjd** [comment]
I assume that the top-level not is effectively *AND NOT ANY*? I think that should cover all of our current use-cases without being overly complex - I like it.

Maybe for UI copy something like:
**Except** if the data matches **ANY** of the following criteria:

**Comment by kofalt** [comment]
No objection
