### ISSUE TITLE
fw_core_log_message_count is not counting all logs

### ISSUE THREAD

**Issue by ryansanford** [flywheel-io/core#1317]
With setting `SCITRAN_CORE_LOG_LEVEL=debug` and many debug messages being printed on an active system, these are the only fw_core_log_message_count records being returned by `/api/metrics`

```
fw_core_log_message_count{level="WARNING",name="elasticsearch"} 84.0
fw_core_log_message_count{level="ERROR",name="scitran.api"} 2.0
```

Discovered when smoke-testing feature https://github.com/flywheel-io/core/pull/1267/files

**Comment by ehlertjd** [comment]
It counts WARN and higher only [by design](https://github.com/flywheel-io/core/pull/1267/files#diff-e758df337485eec65486e93246c5a227R6) - is useful to capture anything lower than WARN, or just unexpected that we don't?
