### ISSUE TITLE
Allow the setting of tags via engine upload metadata

### ISSUE THREAD

**Issue by nagem** [flywheel-io/core#1422]
Tags are not currently an allowable field in the metadata input json schema for the engine. There has been a customer request to allow this behavior, specifically for classification gears that wish to tag containers (sessions) based on information in file headers. A potential list of containers to allow this behavior would be:
  - [x] file
  - [x] acquisition
  - [x] session
  - [x] subject
  - [x] project

Open questions:
  - How to handle tags that are not in the group's tag pool?
    - Rejecting the entire engine result (400) seems extreme. Maybe just remove tags that are not allowed? That behavior might not be expected by the user and go unnoticed.
  - Does is create a union of existing tags and those provided in the metadata or replace existing tags?
    - Create a union

**Comment by nagem** [comment]
@lmperry you can track this ticket here.

**Comment by ehlertjd** [comment]
I think it should treat tags as for the SDK, which is to say just add them.

**Comment by lmperry** [comment]
Has this been assigned to a sprint, or is there any idea of an ETA for this? I have to make some gear modifications and wondering if I should plan on having this available soon.

**Comment by LinaJohnson** [comment]
@lmperry I don't think I'll realistically be able to get around to this one this sprint. I can try but I have a lot on my plate right now. I can make it a priority next sprint if it doesn't get reassigned.

**Comment by nagem** [comment]
@lmperry it is a very small change, I'll reassign it to another developer if one frees up this sprint. I'd say there is a 50% chance it gets done next week.

**Comment by LinaJohnson** [comment]
@lmperry just a update: i was able to pause some of my work and pick this one back up there should be a PR open soon and hopefully we can get it merged by the end of the sprint.

**Comment by LinaJohnson** [comment]
@lmperry this is merged in!
