### ISSUE TITLE
User member of project, but not group, gets permissions errors with SDK and CLI

### ISSUE THREAD

**Issue by jeffyager** [flywheel-io/core#1473]
If a user has access to a project, but is not a member of the group containing the project, SDk and CLI commands like `fw.lookup`, and `fw ls` return with permissions errors. 

My gmail account was a member of the project, but not the group here:
```C02W39YBHTD6:~ jeffyager$ fw login staging2.dev.flywheel.io:L4Wi0j0cxNOlK0XBLL
You are now logged in as Jeff Yager-Gmail!
C02W39YBHTD6:~ jeffyager$ fw status
You are currently logged in as Jeff Yager-Gmail to https://staging2.dev.flywheel.io
C02W39YBHTD6:~ jeffyager$ fw ls
C02W39YBHTD6:~ jeffyager$ fw ls Daniel_Context
(404) No Daniel_Context group found.
C02W39YBHTD6:~ jeffyager$ fw ls kimmel
(403) Not authorized`
```

This was causing search irregularities for Brian Wandell and a UPenn user.

**Comment by nagem** [comment]
Pull in @ehlertjd as necessary, I know he recently reworked the path resolver code.

**Comment by nagem** [comment]
It's likely something else is to blame for the search issue - MC might not be indexing as expected. The only permissions that get saved on a document are the project permissions.

**Comment by hkethi002** [comment]
So from what I gather, there's two issues here, search behaving differently between the browser and the sdk, and the resolver not using project permissions for lookups. Am I following this correctly?

**Comment by nagem** [comment]
> resolver not using project permissions for lookups

This is correct

For the first, there has been a report that a customer in a project but not in a group can't see the project in results from search, UI or otherwise. 

I commented that I think that might be related to an issue with MC being down, not with the logic itself.
