### ISSUE TITLE
Intent pattern for mongo query modification

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#227]
<a href="https://github.com/kofalt"><img src="https://avatars0.githubusercontent.com/u/265071?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kofalt](https://github.com/kofalt)**
_Wednesday Mar 30, 2016 at 20:24 GMT_
_Originally opened as https://github.com/scitran/core/issues/227_

----

Right now, the permchecking and other operations are mainly via closure generators that can be wrapped inside each other. The team reacted positively to an alternative approach:

```
intent.get.query({}).permcheck({}).done()
```

Each successive call returns a new copy of an object recording the intent (query and its options), the final function maps everything together and returns the result.

Filed per request from team discussion, although this sat in my notes for awhile.

**Comment by nagem** [comment]
Tagging @hkethi002 and @ehlertjd and closing.
