### ISSUE TITLE
Combine auth/upload/download tokens to one mongo collection

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#294]
<a href="https://github.com/nagem"><img src="https://avatars2.githubusercontent.com/u/5702596?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nagem](https://github.com/nagem)**
_Thursday May 12, 2016 at 16:20 GMT_
_Originally opened as https://github.com/scitran/core/issues/294_

----

Create generic collection `tokens` with a `type` field containing auth/upload/download

**Comment by ehlertjd** [comment]
Arguably could put upload/download together, but this doesn't give us any value
