### ISSUE TITLE
Add search status endpoint

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#396]
<a href="https://github.com/kofalt"><img src="https://avatars0.githubusercontent.com/u/265071?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kofalt](https://github.com/kofalt)**
_Thursday Aug 11, 2016 at 18:04 GMT_
_Originally opened as https://github.com/scitran/core/issues/396_

----

A public endpoint that always returns 200, providing information about the current status of our elastic search component. Used to know if search is:
1. Healthy - ready for queries
2. Indexing - search results may be incomplete
3. Error - connection failed or other problem

Intention is that you could poll `/status/search` or whatever until healthy is returned.

``` js
{
    status: "healthy | indexing | error"
}
```

May be relevant to @ryansanford. ~~Blocker for NIH work.~~

**Comment by nagem** [comment]
@hkethi002 I dug up this old ticket, might be somewhat useful in your current service status work. I'll let you close it when you complete it :)

**Comment by nagem** [comment]
Closed via #1508
