### ISSUE TITLE
Proposal for MR data classification

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#402]
<a href="https://github.com/gsfr"><img src="https://avatars3.githubusercontent.com/u/712594?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gsfr](https://github.com/gsfr)**
_Saturday Aug 13, 2016 at 05:32 GMT_
_Originally opened as https://github.com/scitran/core/issues/402_

----

The purpose of this classification proposal is to capture how users _think_ about their data and how they would want to _search_ for it, but not to be a ground truth, MR physics-based classification that could be used by processing algorithms.

MR data will be classified according to the following **aspects**, which are all multi-select.

- **Contrast:** B0, B1, T1, T2, T2*, PD, MT, ASL, Perfusion, Diffusion, Spectroscopy, Susceptibility, Velocity, Fingerprinting
- **Intent:** Localizer, Shim, Calibration, Fieldmap, Structural, Functional, Screenshot, Non-Image
- **Features:** Quantitative, Multi-Shell, Multi-Echo, Multi-Flip, Multi-Band, Steady-State, 3D, Compressed-Sensing, Eddy-Current-Corrected, Fieldmap-Corrected, Gradient-Unwarped, Motion-Corrected, Physio-Corrected, Derived, In-Plane, Phase, Magnitude

---

Beyond Neuro MR...

- **Specimen:** Phantom, Human, Animal, [or list of animals]
- **Anatomy:** Head, Neck, Upper Extremities, Chest, Abdomen, Spine, Pelvis, Lower Extremities, Other

---

Next steps:
- get input from more users
- define mappings for all BIDS types
- consider renaming `measurements` DB key to `classification`

---
WIP Conversion table:

Current Classification | Contrast | Intent | Features
----------------------|----------|-------|---------
anatomy_inplane | T1 | Structural | In-Plane
anatomy_ir | | Structural| 
anatomy_pd | PD | Structural |
anatomy_t1w | T1 | Structural | 
anatomy_t2w | T2 | Structural | 
calibration | | Calibration | 
coil_survey | B1 | Calibration | 
diffusion | Diffusion | Structural |
diffusion_map | Diffusion | Structural | Derived
field_map | B0 | Fieldmap | 
functional | T2* | Functional | 
functional_map |  | Functional | Derived
high_order_shim |  | Shim | 
localizer | T2 | Localizer | 
perfusion | Perfusion | |
spectroscopy | Spectroscopy |  | 
screenshot | | Screenshot |

**Comment by gsfr** [comment]
👍 on adding a Phase feature.

Should we also add Magnitude as the counterpart?

**Comment by ehlertjd** [comment]
@gsfr Good question, it may be worth providing the option of explicitly calling out Magnitude as opposed to relying on the understanding that if it's not Phase then it must be Magnitude.

**Comment by gsfr** [comment]
Exactly. Even if we can't set it automatically and it is implied in most situations, having it will be helpful when in direct contrast with phase images.

**Comment by ehlertjd** [comment]
@gsfr Added the beginnings of a conversion table. Related to #1010. 

Would you consider `Inversion-Recovery` to be a feature or an Intent (and if it isn't an intent, does `Inversion-Recovery` imply a Fieldmap intent?)

Somewhat related - does `Spin-Echo` fit in as a feature?

And related to Fieldmaps/Phase -- BIDS has the concept of a precomputed phase difference image - should that be captured as the feature `Phasediff` or `Phase-Difference`?

**Comment by ehlertjd** [comment]
This has shipped
