### ISSUE TITLE
Documentation for scitran/core

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#407]
<a href="https://github.com/coltonlw"><img src="https://avatars1.githubusercontent.com/u/20908947?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [coltonlw](https://github.com/coltonlw)**
_Tuesday Aug 16, 2016 at 13:54 GMT_
_Originally opened as https://github.com/scitran/core/issues/407_

----

- [x] Clearly outline difference between scitran.github.io  and scitran.github.io/core
- [x] Decide what to use or not use the github project wiki for
- [ ] Define index layout for scitran.github.io/core
- [x] Find home for coding standards and new API resource creation process
- [ ] Document work items for frontend developers to style the docs and API console
- [ ] When styling the API console, adhere to the license paying special attention to section 3.3. See   https://github.com/scitran/core/issues/415#issuecomment-241008204

**Comment by ehlertjd** [comment]
This should all be covered with current docs and swagger docs
