### ISSUE TITLE
Listing jobs does not translate "inputs" field from DB representation to Job model representation

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#420]
<a href="https://github.com/coltonlw"><img src="https://avatars1.githubusercontent.com/u/20908947?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [coltonlw](https://github.com/coltonlw)**
_Monday Aug 22, 2016 at 13:15 GMT_
_Originally opened as https://github.com/scitran/core/issues/420_

----

When a new Job is added, the inputs property is an object.  When JobsHandler saves the job to the database, it translates "inputs" property to an array of objects.  https://github.com/scitran/core/blob/master/api/jobs/jobs.py#L147

@nagem Can you explain why we made this change?  In a comment in database.py you reference scitran/core issue #363 , I wasn't sure what the relation was.

https://github.com/scitran/core/commit/85eb1c110239e2936b68e485e3c777e9cba3275a

**Comment by nagem** [comment]
This issue was fixed.
