### ISSUE TITLE
Introduce scheduled_run_time for job documents

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#427]
<a href="https://github.com/ryansanford"><img src="https://avatars1.githubusercontent.com/u/15736230?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryansanford](https://github.com/ryansanford)**
_Tuesday Aug 23, 2016 at 14:21 GMT_
_Originally opened as https://github.com/scitran/core/issues/427_

----

It is not intuitive that `jobs/next` returns jobs ordered by their modification time, and that updating a job would drop it to the bottom of the queue.

Suggest introducing a scheduled_run_time field that defaults to the creation datetime, but can be set when creating jobs by hand.

Beyond decoupling execution order from modification time, this would enable a single ordered query for the jobs now flag, and enable certain jobs to be queued for delayed execution, such as nights and weekends.

Priority is currently not urgent.

**Comment by nagem** [comment]
We should design a queue system that meets many needs, some much more complex than this one. Closing, with the intention of eventually opening a ticket that better tracks the design necessary.
