### ISSUE TITLE
Design process for writing documentation

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#445]
<a href="https://github.com/coltonlw"><img src="https://avatars1.githubusercontent.com/u/20908947?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [coltonlw](https://github.com/coltonlw)**
_Tuesday Aug 30, 2016 at 16:55 GMT_
_Originally opened as https://github.com/scitran/core/issues/445_

----

Github pages only supports hosting HTML.  If we want to use our Github Pages site to host docs for our whole project, we need a way to write the documentation in something like markdown, and then convert it to HTML.  Sphinx generates HTML from RST.  It can also be used to generate HTML from markdown.  This issue is to dicsuss what want to do here 

Sphinx markdown:  https://github.com/ericholscher/sphinx-markdown-test
Docs for "requests" package, generated from RST using Sphinx:  http://docs.python-requests.org/en/master/
https://github.com/kennethreitz/requests/tree/master/docs
EDIT:  Found this tool for generating docs with markdown outside of sphinx:  http://www.mkdocs.org/
@gsfr

**Comment by ehlertjd** [comment]
Closing - swagger and SDK docs should fill in the gaps.
