### ISSUE TITLE
Issue with concurrent uploads

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#591]
<a href="https://github.com/cgc"><img src="https://avatars0.githubusercontent.com/u/1276728?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cgc](https://github.com/cgc)**
_Monday Nov 07, 2016 at 23:37 GMT_
_Originally opened as https://github.com/scitran/core/issues/591_

----

When I run one upload, I usually get a success. When running two uploads in parallel, I get a 500, "No such file or directory: /var/scitran/data/.tmp$RAND/myfile.txt". While I don't see explicit `cleanup()` of the tmpdir in `placer.py`, I wonder if there's just some strange GC issue that is causing the variable to be collected? I'll check out the logs with @gsfr later. approximate time of errors: Nov 7 23:20 UTC

**Comment by nagem** [comment]
Closing as "outdated". In the current system, many uploads run in parallel without issue.
