### ISSUE TITLE
Centralize then improve persistence & handler layers

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#616]
<a href="https://github.com/kofalt"><img src="https://avatars0.githubusercontent.com/u/265071?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kofalt](https://github.com/kofalt)**
_Tuesday Dec 13, 2016 at 18:14 GMT_
_Originally opened as https://github.com/scitran/core/issues/616_

----

Rough outline of ambitious goals in collaboration with @nagem. Ticket description in flux!

1. Qualitative: achieve all container database access routes through ContainerStorage; all container handlers route through ContainerHandler.

2. ContainerHandler broken into classes, similar to ContainerStorage. (Maybe this phase comes later?)

3. ContainerStorage logic turns into named objects (Session, etc) that subclass dict. Advantage: properties are still a map, not named, so interfacing logic doesn't change!

4. Evaluate result. Stick with subclassed dicts? Change to named properties?

5. Evaluate folding job persistence layer into same hierarchy. Does it make sense?

6. Do handlers get much cooler with this layout? (Hint: yes)

**Comment by nagem** [comment]
Outdated views on the matter, closing.
