### ISSUE TITLE
Add "Modalities" endpoints, Classification support

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#647]
<a href="https://github.com/nagem"><img src="https://avatars2.githubusercontent.com/u/5702596?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nagem](https://github.com/nagem)**
_Monday Jan 30, 2017 at 21:38 GMT_
_Originally opened as https://github.com/scitran/core/issues/647_

----

Relates to #402 

- [x] Add `modalities` collection in Mongo with appropriate REST endpoints. Will store the individual modalities (MR, PHYSIO, etc) and a map of it's available classification options
- [x] Existing `measurements` field will be renamed to `classification(s?)` which is a map
- [x] User can modify `info`, `modality` and `classification` attributes of an existing file
- [x] Ensure search works as expected after update
- [x] Modify session template logic to reflect new classification attribute
- [x] Classification for MR data is based on 3 attributes. User can manually update Contrast, Intent, and Features. These fields are optional and users can select 0 to many options from each dropdown. For additional information see https://github.com/scitran/core/issues/402

**Comment by nagem** [comment]
Complete via #1010
