### ISSUE TITLE
Reduce HTTP awareness in non handler layers

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#66]
<a href="https://github.com/rentzso"><img src="https://avatars3.githubusercontent.com/u/1427389?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rentzso](https://github.com/rentzso)**
_Wednesday Nov 18, 2015 at 23:57 GMT_
_Originally opened as https://github.com/scitran/core/issues/66_

----

As a general rule, classes should fall into two distinct categories:
- Classes that have functions named after HTTP verbs, and (basically) nothing else
- Classes that don't know anything about HTTP verbs or protocol details

Rather than self.abort, raise a variety of typed exceptions. This would be a better, drop-in replacement for what self.abort does anyway. At the very top, and/or whichever layers are appropriate, catch typed exceptions and handle a JSON error return there.

**Comment by ehlertjd** [comment]
Most concerns have been captured in other tickets
