### ISSUE TITLE
Orginary users are not allowed to `GET /users/<x>`

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#660]
<a href="https://github.com/kofalt"><img src="https://avatars0.githubusercontent.com/u/265071?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kofalt](https://github.com/kofalt)**
_Friday Feb 10, 2017 at 00:54 GMT_
_Originally opened as https://github.com/scitran/core/issues/660_

----

You cannot retrieve any user other than yourself, despite the response not having any sensitive fields.

**Comment by nagem** [comment]
This has been fixed.
