### ISSUE TITLE
Doc driven tests (abao) have maintenance issues

### ISSUE THREAD

**Issue by flywheel-bot** [flywheel-io/core#664]
<a href="https://github.com/ryansanford"><img src="https://avatars1.githubusercontent.com/u/15736230?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryansanford](https://github.com/ryansanford)**
_Monday Feb 13, 2017 at 20:43 GMT_
_Originally opened as https://github.com/scitran/core/issues/664_

----

Pain points to investigate
- [ ] Output schema file organization not intuitive
  - @nagem Provide context on pain with output schemas
- [ ] Order of execution is arbitrary 
  - confirmed due to js async loading
  - in practice, order has followed order in api.raml and sub raml files. Might be output printing only?
- [ ] Test inputs are managed in file location separate from the RAML documentation
  - confirmed that example in raml used
  - @ambrussimon-invenshure confirm if raml allows 1 example per result code
- [x] Dependency on prior execution of python or newman integration tests
  - Use common fixure loader for each test, rather than dependencies between test suites
  - Re-organize test scripts to support independent execution
  -  Postman tests alone satisfy abao
  - Test gear created with both postman tests and python integration

**Comment by nagem** [comment]
Abao has been removed
